# 项目相关配置
wlwq:
  # 名称
  name: 眼镜
  # 版本
  version: 0.0.1
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: false
  # 文件路径
  profile: /mnt/uploadPath
#  profile: D:/wlwq/uploadPath
  # 获取ip地址开关
  addressEnabled: false

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8200
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    alb: error
    org.springframework: error

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 39.101.66.18
    # 端口，默认为6379
    port: 6379
    # 密码
#    password: p@s5w0rd
    password: 123456
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# 进线池队列消费者接受周期(秒)
#incomingPool:
#  delay: 10

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: Renbowen
  # 令牌有效期（默认30分钟）
  expireTime: 600

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: alb.project.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*,/vacation/*

# 代码生成
gen:
  # 作者
  author: Renbowen
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: alb.project.vacation
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_

# 配置文件明文密码加密
#jasypt:
#  encryptor:
#    password: Renbowen # 自定义加密密钥
#    property:
#      prefix: Renbowen( # 自定义加密前缀
#      suffix: ) # 自定义加密后缀
#    bean: codeSheepEncryptorBean # 自定义加密器

# 阿里云短信模板
aliyunSms:
  templateRegist: SMS_148375326 # 注册
  templateUpdatePassword: SMS_148375325 # 修改密码
  templateInformationChange: SMS_148375324 # 信息变更
  templateAuthentication: SMS_148375329 # 身份验证
  templateLoginVerify: SMS_148375328 # 登录确认
  templateLoginException: SMS_148375327 # 登录异常

# H5分享链接
shareUrl: https://mini.milido.cn/api/page?sourceType=